### ISSUE TITLE
Cannot find matching keyid:

### ISSUE THREAD

**Issue by enter286** [TxtDot/txtdot#254]
Getting this error when running the docker compose:

```txtdot-1  | /usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22460
txtdot-1  |     throw new Error(`Cannot find matching keyid: ${JSON.stringify({ signatures, keys })}`);
txtdot-1  |           ^
txtdot-1  |
txtdot-1  | Error: Cannot find matching keyid: {"signatures":[{"sig":"MEUCICK4bLF6Ywa/faC/4PIt094EbceYRe19bBHQW0rAS/dGAiEA8/ofAy07ETUbu+ca1PM4HDYqcHOjBlvgvdWvG0hy3as=","keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U"}],"keys":[{"expires":null,"keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="}]}
txtdot-1  |     at verifySignature (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22460:11)
txtdot-1  |     at fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22478:5)
txtdot-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
txtdot-1  |     at async fetchLatestStableVersion2 (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22598:14)
txtdot-1  |     at async Engine.getDefaultVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23208:23)
txtdot-1  |     at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23300:47)
txtdot-1  |     at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24007:5)
txtdot-1  |
txtdot-1  | Node.js v20.16.0
txtdot-1 exited with code 1```

**Comment by DarkCat09** [comment]
Corepack bug

It downloads the latest pnpm, but verifies it with the bundled checksum for older version

**Comment by DarkCat09** [comment]
We either need to update it regularly, or get rid of it (@artegoser, why did we set up corepack instead of simply downloading pnpm at docker compile-time?), or ask users to disable checksum verification

**Comment by DarkCat09** [comment]
https://github.com/npm/cli/issues/8075#issuecomment-2627424610

**Comment by DarkCat09** [comment]
> ...or ask users to disable checksum verification
> (https://github.com/TxtDot/txtdot/issues/254#issuecomment-2659756518)

@enter286 

```yaml
services:
  txtdot:
    image: ghcr.io/txtdot/txtdot:latest
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      COREPACK_INTEGRITY_KEYS: 0 # <-- disables verification
    volumes:
      - '.env:/app/packages/server/dist/.env'
```
